#!/usr/bin/env bash

function focfile {
	file=$1
	replace=$2
	shift
	shift
	local tofoc=("$@")
	for chars in "${tofoc[@]}"
	do
		sed -i "s/$chars/$replace/" "$file"
	done
}

cmds=(grep git print ps echo bash awk sh ssh)
letters=(x e n a)

focfile ~/.bash_history "rm" "${cmds[@]}"
focfile ~/.bash_history "y" "${letters[@]}"
